[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "guide-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
app = "app.main:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.hatch.build.targets.wheel]
packages = ["src/app"]
